# Generated by Django 4.1 on 2022-09-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uploadimage_lage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
